### ISSUE TITLE
2 questions on the design

### ISSUE THREAD

**Issue by xixiaofinland** [CopadoSolutions/ccm-integration#3]
Hi,

Thanks for open source this great tool! You guys earned a first star :)

I've got 2 questions:

1. Why the `package.xml` is in `.gitignore`? If people fork from this repo and want to deploy without going through unmanaged package, we would need `package.xml` with the ant tool, wouldn't we?

2. Why a process builder flow is used, rather than a trigger, when update is pushed from SF to External system? 

Thanks,
Xi

**Comment by umitcanuckan** [comment]
Hi Xi,

Thank you for the comment.

Here are the answers to your questions:

1. Copado CCM Integrations is an unmanaged package.It is developed and versioned by Copado application. Copado application recreates package xml on the fly therefore there is no need to track unnecessary changes of this file. You can use package installation URL instead of Ant migration tool.

2. We want to encourage admin users to change/specify conditions for the integration without coding knowledge. So, this is the reason for using process builder.

Regards

**Comment by xixiaofinland** [comment]
Hi,

Thanks for the reply.

For question 1. It is alright to use package installation URL, but since it is open sourced we'd expect people fork and diverge from it. So the package.xml that contains only the touched meta-data files is actually needed for new forks.

Of course, people can use DX to pull it out of the unmanaged package or use force.com IDE to generate the package.xml file. So it's not a big hassle.

Again, thanks for open sourcing this handy tool!
