### ISSUE TITLE
Can I import sprint field

### ISSUE THREAD

**Issue by shaffiruddin** [CopadoSolutions/ccm-integration#4]
Is it possible to import sprint field from jira into copado sprint lookup field

**Comment by drcopa** [comment]
Hello @shaffiruddin, yes this is possible. 
There are 2 options:
1. Import the JIRA Sprint Id or name and save it in a text field in the Copado User Story for having a simple reference
2. Import the JIRA Sprints and create corresponding Sprint records in Copado. Then when fetching the User Stories from JIRA, link them to their corresponding Sprint in Copado.

Since this is an open source package, you can create a pull request with your Sprint implementation and we can include it in the package for others to leverage your code.

**Comment by colePrato-zz** [comment]
@shaffiruddin  were you able to figure out how to make this work? I am running into the same issue and before I start working on this.

**Comment by umitcanuckan** [comment]
Please visit our community and and utilize our newly released Unlocked package under Copado Labs for Sprint fetch.

Regards
